export const Confirm = `Confirmar`;
export const ConfirmationCode = `Código de confirmación`;
export const ConfirmationCodeSent = `Hemos enviado el código de confirmación al teléfono`;
export const Continue = `Continuar`;
export const EnterHereConfirmationCode = `Ingresa aquí el código de seis dígitos`;
export const ErrorInvalidVerificationCode = `El código de verificación de SMS utilizado para crear la credencial de autenticación del teléfono no es válido. Vuelva a enviar el código de verificación sms y asegúrese de usar el código de verificación proporcionado por el usuario.`;
export const ErrorDefault = `Ha ocurrido un error por favor intenta de nuevo.`;
export const PhoneNumber = `Número de Teléfono`;
export const RecaptchaContainer = `recaptcha-container`;
export const SelectCountry = `Selecciona tu país`;
export const ErrorEmailAlreadyExists = 'Otro usuario ya está utilizando el correo electrónico proporcionado. Cada usuario debe tener un correo electrónico único.'
export const ErrorInsufficientPermission = 'La credencial que se usó para inicializar el SDK de Admin no tiene permisos suficientes a fin de acceder al recurso de autenticación solicitado. Consulta cómo configurar un proyecto de Firebase para ver la documentación sobre cómo generar una credencial con los permisos apropiados y usarla en la autenticación de los SDK de Admin.'
export const ErrorInternalError = 'El servidor de autenticación encontró un error inesperado cuando se intentaba procesar la solicitud. Para obtener información adicional, revisa la respuesta del servidor de autenticación, que debería estar incluida en el mensaje de error. Si el error persiste, avísanos mediante nuestro canal de asistencia de informe de errores.'
export const ErrorInvalidCredential = 'La credencial que se usa en la autenticación de los SDK de Admin no se puede emplear para realizar la acción deseada. Algunos métodos de autenticación, como createCustomToken() y verifyIdToken(), requieren que los SDK se inicialicen con una credencial de certificado en lugar de un token de actualización o una credencial predeterminada de la aplicación. Consulta Inicializa el SDK para ver documentación sobre cómo autenticar el SDK de Admin con una credencial de certificado.'
export const ErrorInvalidDisplayName = 'El valor que se proporcionó para la propiedad del usuario displayName no es válido. Debe ser una string que no esté vacía.'
export const ErrorInvalidEmail = 'El valor que se proporcionó para la propiedad del usuario email no es válido. Debe ser una dirección de correo electrónico de string.'
export const ErrorInvalidEmailVerified = 'El valor que se proporcionó para la propiedad del usuario emailVerified no es válido. Debe ser un booleano.'
export const ErrorInvalidPassword = 'El valor que se proporcionó para la propiedad del usuario password no es válido. Debe ser una string con al menos seis caracteres.'
export const ErrorInvalidPhoneNumber = 'El valor que se proporcionó para phoneNumber no es válido. Debe ser una string de identificador que no esté vacía y que cumpla con el estándar E.164.'
export const ErrorInvalidPhotoUrl = 'El valor que se proporcionó para la propiedad del usuario photoURL no es válido. Debe ser una URL de string.'
export const ErrorInvalidUserImport = 'El registro de usuarios para importar no es válido.'
export const ErrorMaximumUserCountExceeded = 'Se excedió la cantidad máxima de usuarios permitidos para importar.'
export const ErrorOperationNotAllowed = 'El proveedor de acceso proporcionado está inhabilitado para tu proyecto de Firebase. Habilítalo en la sección Método de acceso de Firebase console.'
export const ErrorPhoneNumberAlreadyExists = 'Otro usuario ya utiliza el phoneNumber proporcionado. Cada usuario debe tener un phoneNumber único.'
export const ErrorUnauthorizedContinueUri = 'El dominio de la URL de continuación no está en la lista blanca. Inclúyelo en la lista en Firebase console.'
export const ErrorUserNotFound = 'No existe ningún registro de usuario que corresponda al identificador proporcionado.'
